[build]
  base = ""  # Adjust this if your project directory is different
  command = "CI=false npm run build"
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200